version: "3.8"
services:
  backend:
    build:
      context: ./backend
      args:
        - NODE_ENV=${NODE_ENV}
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_DB=${MONGO_DB}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}